/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module controlunit_19 (
    input clk,
    input irq,
    input z,
    input reset,
    input [5:0] opcode,
    output reg [2:0] pcsel,
    output reg wasel,
    output reg asel,
    output reg ra2sel,
    output reg bsel,
    output reg [5:0] alufn,
    output reg [1:0] wdsel,
    output reg werf,
    output reg moe,
    output reg xwr
  );
  
  
  
  localparam CU_ROM = 1152'h70011c00470011c00470011c00470011c00470011c00470011c00470011c00470011c00470011c00470011c00470011c00470011c00402058180170011000470010800400010235600030002c00130006c01ab0072c01eb1c00400c3003cc00b30034c01030042c011b1c00402030082c02130086c03ab00f2c03eb1c00402c300bcc02b31c004030300c2c031b1c004;
  
  reg M_irq_sampler_d, M_irq_sampler_q = 1'h0;
  
  always @* begin
    M_irq_sampler_d = M_irq_sampler_q;
    
    M_irq_sampler_d = irq;
    pcsel = CU_ROM[(opcode)*18+15+2-:3];
    wasel = CU_ROM[(opcode)*18+14+0-:1];
    asel = CU_ROM[(opcode)*18+13+0-:1];
    ra2sel = CU_ROM[(opcode)*18+12+0-:1];
    bsel = CU_ROM[(opcode)*18+11+0-:1];
    alufn = CU_ROM[(opcode)*18+5+5-:6];
    wdsel = CU_ROM[(opcode)*18+3+1-:2];
    werf = CU_ROM[(opcode)*18+2+0-:1];
    moe = CU_ROM[(opcode)*18+1+0-:1];
    xwr = CU_ROM[(opcode)*18+0+0-:1];
    if (opcode == 6'h1d && z == 1'h1) begin
      pcsel = 3'h1;
    end else begin
      if (opcode == 6'h1e && z == 1'h0) begin
        pcsel = 3'h1;
      end
    end
    if (reset) begin
      xwr = 1'h0;
      werf = 1'h0;
    end
    if (M_irq_sampler_q == 1'h1) begin
      pcsel = 3'h4;
      wasel = 1'h1;
      werf = 1'h1;
      wdsel = 2'h0;
      xwr = 1'h0;
    end
  end
  
  always @(posedge clk) begin
    M_irq_sampler_q <= M_irq_sampler_d;
  end
  
endmodule
