/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module regfile_28 (
    input rst,
    input clk,
    input [4:0] write_address_1,
    input [15:0] write_data_1,
    input write_enable_1,
    input [4:0] write_address_2,
    input [15:0] write_data_2,
    input write_enable_2,
    input [4:0] write_address_3,
    input [15:0] write_data_3,
    input write_enable_3,
    input [4:0] write_address_4,
    input [15:0] write_data_4,
    input write_enable_4,
    output reg [511:0] out
  );
  
  
  
  reg [511:0] M_registers_d, M_registers_q = 1'h0;
  
  always @* begin
    M_registers_d = M_registers_q;
    
    if (write_address_1 != 5'h00 && write_enable_1) begin
      M_registers_d[(write_address_1)*16+15-:16] = write_data_1;
    end
    if (write_address_2 != 5'h00 && write_enable_2) begin
      M_registers_d[(write_address_2)*16+15-:16] = write_data_2;
    end
    if (write_address_3 != 5'h00 && write_enable_3) begin
      M_registers_d[(write_address_3)*16+15-:16] = write_data_3;
    end
    if (write_address_4 != 5'h00 && write_enable_4) begin
      M_registers_d[(write_address_4)*16+15-:16] = write_data_4;
    end
    out = M_registers_q;
    if (rst) begin
      M_registers_d = 512'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
    end
  end
  
  always @(posedge clk) begin
    M_registers_q <= M_registers_d;
  end
  
endmodule
