/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module regfile_18 (
    input clk,
    input [4:0] read_address_1,
    input [4:0] read_address_2,
    output reg [15:0] read_data_1,
    output reg [15:0] read_data_2,
    input [4:0] write_address,
    input [15:0] write_data,
    input write_enable
  );
  
  
  
  reg [511:0] M_registers_d, M_registers_q = 1'h0;
  
  always @* begin
    M_registers_d = M_registers_q;
    
    read_data_1 = M_registers_q[(read_address_1)*16+15-:16];
    read_data_2 = M_registers_q[(read_address_2)*16+15-:16];
    if (write_address != 4'h0 && write_enable) begin
      M_registers_d[(write_address)*16+15-:16] = write_data;
    end
    if (read_address_1 == 4'h0) begin
      read_data_1 = 1'h0;
    end
    if (read_address_2 == 4'h0) begin
      read_data_2 = 1'h0;
    end
  end
  
  always @(posedge clk) begin
    M_registers_q <= M_registers_d;
  end
  
endmodule
