/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module comparator_8 (
    input z,
    input v,
    input n,
    input [5:0] alufn,
    output reg cmp
  );
  
  
  
  always @* begin
    cmp = 1'h0;
    
    case (alufn[1+1-:2])
      2'h1: begin
        cmp = z;
      end
      2'h2: begin
        cmp = n ^ v;
      end
      2'h3: begin
        cmp = n ^ v;
      end
    endcase
  end
endmodule
