/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module comparator_24 (
    input z,
    input v,
    input n,
    input [5:0] alufn,
    output reg cmp
  );
  
  
  
  reg i;
  reg j;
  
  always @* begin
    i = n ^ v;
    j = i | z;
    cmp = 1'h0;
    
    case (alufn[0+3-:4])
      4'h5: begin
        cmp = z;
      end
      4'h9: begin
        cmp = i;
      end
      4'hd: begin
        cmp = j;
      end
    endcase
  end
endmodule
