/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module rand_gen_22 (
    input clk,
    input rst,
    input [3:0] num,
    output reg [4:0] randint
  );
  
  
  
  wire [16-1:0] M_alu_out;
  wire [3-1:0] M_alu_zvn;
  wire [20-1:0] M_alu_seg;
  reg [16-1:0] M_alu_a;
  reg [16-1:0] M_alu_b;
  reg [6-1:0] M_alu_alufn;
  alu_12 alu (
    .a(M_alu_a),
    .b(M_alu_b),
    .alufn(M_alu_alufn),
    .out(M_alu_out),
    .zvn(M_alu_zvn),
    .seg(M_alu_seg)
  );
  
  wire [32-1:0] M_randseed_value;
  counter_29 randseed (
    .clk(clk),
    .rst(rst),
    .value(M_randseed_value)
  );
  localparam START_game_step = 2'd0;
  localparam RAND_game_step = 2'd1;
  localparam DONE_game_step = 2'd2;
  
  reg [1:0] M_game_step_d, M_game_step_q = START_game_step;
  localparam BITMASK_rand_step = 2'd0;
  localparam MULTIPLY_rand_step = 2'd1;
  localparam EXTRACT_rand_step = 2'd2;
  
  reg [1:0] M_rand_step_d, M_rand_step_q = BITMASK_rand_step;
  reg [4:0] M_randint1_d, M_randint1_q = 1'h0;
  reg [15:0] M_randint_temp_d, M_randint_temp_q = 1'h0;
  wire [32-1:0] M_rand_gen_num;
  reg [1-1:0] M_rand_gen_next;
  reg [32-1:0] M_rand_gen_seed;
  pn_gen_28 rand_gen (
    .clk(clk),
    .rst(rst),
    .next(M_rand_gen_next),
    .seed(M_rand_gen_seed),
    .num(M_rand_gen_num)
  );
  
  always @* begin
    M_game_step_d = M_game_step_q;
    M_rand_step_d = M_rand_step_q;
    M_randint_temp_d = M_randint_temp_q;
    M_randint1_d = M_randint1_q;
    
    M_rand_gen_next = 1'h1;
    M_rand_gen_seed = M_randseed_value;
    M_alu_alufn = 6'h00;
    M_alu_a = 16'h0000;
    M_alu_b = 16'h0000;
    randint = 1'h0;
    
    case (M_game_step_q)
      START_game_step: begin
        M_randint1_d = 1'h0;
        M_rand_gen_next = 1'h1;
        M_alu_a = 1'h0;
        M_alu_b = 1'h0;
        M_alu_alufn = 1'h0;
        M_game_step_d = RAND_game_step;
      end
      RAND_game_step: begin
        
        case (M_rand_step_q)
          BITMASK_rand_step: begin
            M_rand_gen_next = 1'h1;
            M_alu_a = M_rand_gen_num[0+15-:16];
            M_alu_b = 16'h0fff;
            M_alu_alufn = 6'h18;
            M_randint_temp_d = M_alu_out[0+15-:16];
            M_rand_step_d = MULTIPLY_rand_step;
          end
          MULTIPLY_rand_step: begin
            M_alu_a = M_randint_temp_q;
            M_alu_b = num;
            M_alu_alufn = 6'h02;
            M_randint_temp_d = M_alu_out[0+15-:16];
            M_rand_step_d = EXTRACT_rand_step;
          end
          EXTRACT_rand_step: begin
            M_alu_a = M_randint_temp_q;
            M_alu_b = 16'h000c;
            M_alu_alufn = 6'h21;
            M_randint1_d = M_alu_out[0+3-:4];
            M_game_step_d = DONE_game_step;
          end
        endcase
      end
      DONE_game_step: begin
        randint = M_randint1_q + 5'h10;
        if (rst) begin
          M_game_step_d = START_game_step;
        end
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_randint1_q <= 1'h0;
      M_randint_temp_q <= 1'h0;
      M_game_step_q <= 1'h0;
      M_rand_step_q <= 1'h0;
    end else begin
      M_randint1_q <= M_randint1_d;
      M_randint_temp_q <= M_randint_temp_d;
      M_game_step_q <= M_game_step_d;
      M_rand_step_q <= M_rand_step_d;
    end
  end
  
endmodule
